### ISSUE TITLE
Add a dashboard view to see your tokens

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/moodle-enrol_course_tokens#30]
BLOCKER: 

- [x] https://github.com/fulldecent/moodle-enrol_course_tokens/issues/16

---

Add a block which we can add to student's "dashboard" or "my page" showing their course tokens.

This will allow them to find their tokens. Currently their tokens are hidden on a page they do not know about.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Created a new file 'block_course_tokens.php' to display course tokens on the student's dashboard. Modified 'view_tokens.php' to include a function for fetching tokens that can be used in the new block.

You can review changes in this commit: https://github.com/mnmnk43434/fulldecent-moodle-enrol_course_tokens-30/commit/722a7ebac28682ec11cbf7766adb349001e7fb09.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by fulldecent** [comment]
Please see https://github.com/fulldecent/moodle-local_plugin_template/tree/feat-block/block

And I install this by `ln -s` the block folder folder of our module into moodle's blocks plugins folder.

**Comment by Raza403** [comment]
Move the block in the enrol folder.
Sym link it back.
Update readme.

## Follow on work.
Do the same in Moodle template plugin.

**Comment by Raza403** [comment]
Add a link at the bottom. "View individual tokens."

**Comment by fulldecent** [comment]
In production I was expecting to see a folder named `block` inside `enrol/course_tokens`

**Comment by fulldecent** [comment]
And can you please add evidence with screenshots before closing issues?

**Comment by Raza403** [comment]
@fulldecent please run the "sym link" command so that I can add the block.

**Comment by fulldecent** [comment]
I cannnot symlink. The folder is missing.

Please use the folder course_tokens/block for the block plugin files

**Comment by Raza403** [comment]
Renamed the folder to "block". @fulldecent you can symlink now.

**Comment by fulldecent** [comment]
Linking complete

**Comment by Raza403** [comment]
Course tokens block is added, we can close the issue now.
<img width="1430" alt="Screenshot 2024-12-10 at 10 00 27 AM" src="https://github.com/user-attachments/assets/061abd4d-9bc4-4ebe-ba0d-2ecfdbc58cfd">

**Comment by fulldecent** [comment]
Can you please document in the README showing this feature and updating the install instructions?

**Comment by Raza403** [comment]
Updated the readme file, added inf about dashboard block and installation procedure.

**Comment by fulldecent** [comment]
Looks great TY
