### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/moodle-enrol_course_tokens#34]
![Screenshot 2024-12-05 at 11 19 28](https://github.com/user-attachments/assets/58b5ae98-a77d-4def-b3e2-6fb401b7d98d)

**Comment by fulldecent** [comment]
And at bottom please add link to course token detail page

**Comment by Raza403** [comment]
Formatting problems were already resolved. Please delete cache, and refresh.
Strangely we don't have the option to kill the home button. We can do it using CSS option, below is the screenshot about how I did it.
<img width="1423" alt="Screenshot 2024-12-12 at 8 35 44 PM" src="https://github.com/user-attachments/assets/b205e40f-4b42-405f-8850-917b97e7e980" />

**Comment by fulldecent** [comment]
Your approach to kill home button is fine.

Other items still not fixed in your screenshot, please see top post

**Comment by Raza403** [comment]
Are these OK now?
<img width="1118" alt="Screenshot 2024-12-13 at 9 41 06 AM" src="https://github.com/user-attachments/assets/00d926f4-1c72-4257-942d-7d7e937eba93" />
<img width="1440" alt="Screenshot 2024-12-13 at 9 41 20 AM" src="https://github.com/user-attachments/assets/15089d8f-2f79-407a-8603-9f3fe0ae2bcd" />

**Comment by fulldecent** [comment]
Missing the h-center

**Comment by Raza403** [comment]
Horizontal centering is done and the columns equal width.
<img width="1440" alt="Screenshot 2024-12-14 at 11 12 17 AM" src="https://github.com/user-attachments/assets/ef60450b-a2f8-44fa-80d8-a0d2532fa349" />
<img width="1440" alt="Screenshot 2024-12-14 at 11 12 36 AM" src="https://github.com/user-attachments/assets/b2783a6c-625b-44f6-878b-8dc254f9c218" />

**Comment by fulldecent** [comment]
Looks great thank you
