### ISSUE TITLE
activate.php: Abort if student is already enrolled in course

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/moodle-enrol_course_tokens#6]
A student may already be enrolled in a course.

! We need to define exactly what "already enrolled" means in Moodle.

Since tokens are valuable, consumable resources (i.e. they cost somebody money) we should prevent them from being used if they will have no effect.

https://github.com/fulldecent/moodle-local_enrollment_tokens/blob/4cf5d9f03335574ce49b6582130c50bd297d97d9/do-activate-token.php#L70-L71

---

Actually even better is When a student enrolls in a course warn them if they are already enrolled that it will reset their course progress (and show their old completion date) // then allow them to continue or not

**Comment by fulldecent** [comment]
Can you please document in this issue with screenshots before closing issue?

**Comment by Raza403** [comment]
Sure, here are the screenshots:

dashboard.php
![Image](https://github.com/user-attachments/assets/739049eb-a086-49ef-90bb-ed8f2189daf1)

view_tokens.php (When using "Enroll me" option)
![Image](https://github.com/user-attachments/assets/dbd1edbd-f900-48e1-ab7b-9f7aef6a5064)

view_tokens.php (When using "Enroll somebody else" option)
![Image](https://github.com/user-attachments/assets/3cb081ba-3174-4b0a-8fc2-d2057259b99a)
